# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo TeStiNg cUsTom cOmMeNt 1 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    echo TeStiNg cUsTom cOmMeNt 2 ------------------------------
    echo TeStiNg cUsTom cOmMeNt 3 ::::::::::::::::::::::::::::::
    echo TeStiNg cUsTom cOmMeNt 4 ==============================
    echo TeStiNg cUsTom cOmMeNt 5 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  displayName: 'Run a multi-line script'
